///<reference path="../../node_modules/reflect-metadata/reflect-metadata.d.ts"/>"
/// <reference path="../../typings/globals/jquery/index.d.ts" />
/// <reference path="../../typings/modules/body-parser/index.d.ts" />
/// <reference path="../../typings/modules/debug/index.d.ts" />
/// <reference path="../../typings/modules/express/index.d.ts" />
/// <reference path="../../typings/modules/mime/index.d.ts" />
/// <reference path="../../typings/modules/react-bootstrap/index.d.ts" />
/// <reference path="../../typings/modules/react-dom/index.d.ts" />
/// <reference path="../../typings/modules/react-router/index.d.ts" />
/// <reference path="../../typings/modules/react/index.d.ts" />
/// <reference path="../../typings/modules/serve-static/index.d.ts" />